/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_kostia_gtkjfilechooser_GtkVersion */

#ifndef _Included_eu_kostia_gtkjfilechooser_GtkVersion
#define _Included_eu_kostia_gtkjfilechooser_GtkVersion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_kostia_gtkjfilechooser_GtkVersion
 * Method:    check
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_kostia_gtkjfilechooser_GtkVersion_check
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
