/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_X11_GtkFileDialogPeer */

#ifndef _Included_sun_awt_X11_GtkFileDialogPeer
#define _Included_sun_awt_X11_GtkFileDialogPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_GtkFileDialogPeer_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_GtkFileDialogPeer_destroy
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    run
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_X11_GtkFileDialogPeer_run
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    setMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_GtkFileDialogPeer_setMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    setDirectoryNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_GtkFileDialogPeer_setDirectoryNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    setFileNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_GtkFileDialogPeer_setFileNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    setFilenameFilterNative
 * Signature: (Ljava/io/FilenameFilter;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_GtkFileDialogPeer_setFilenameFilterNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_X11_GtkFileDialogPeer
 * Method:    filenameFilterCallbackTest
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_X11_GtkFileDialogPeer_filenameFilterCallbackTest
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
